name: GitHub Pages

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - name: Prepare and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        run: |
          npm i -g npm
          npm i -g @angular/cli typescript angular-cli-ghpages
          ng add --skip-confirmation angular-cli-ghpages
          npm ci
          ng build --configuration production
          cp README.md dist/samuelmarks-github-io
          MSG="$(git show -s --format='%s' "$GITHUB_SHA")"
          email_author="$(git log -1 --pretty=format:'%an <%ce>')"
          author="${email_author% *}"
          git config --global user.name "$author"
          email="${email_author#*<}"; email="${email::-1}"
          git config --global user.email "$email"
          ng deploy samuelmarks-github-io --repo='https://'"$GITHUB_TOKEN"'@github.com/SamuelMarks/SamuelMarks.github.io' --branch='master' --message="$MSG" --name="$name" --email="$email" --no-silent
